#pragma once

#include <LoadBalancing-cpp/inc/Listener.h>

/**
 * \brief The Listener class handles events and callbacks from the network
 * client.
 *
 * This class serves as a listener for events and callbacks generated by the
 * network client. It inherits from the Photon Realtime SDK's Listener class and
 * implements various callback methods to handle different types of events, such
 * as connection status changes, room events, and custom events.
 *
 * The Listener class is responsible for receiving and processing events from
 * the network client and forwarding relevant information to the application
 * logic through the NetworkInterface interface. This decouples the network
 * communication logic from the application logic, allowing for flexibility and
 * extensibility in handling network events.
 */
class Listener final : public ExitGames::LoadBalancing::Listener {
 public:

};